name: otop_mobile_app
description: "OTOP Mobile Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  http: ^1.2.0
  
  # State Management
  provider: ^6.1.2
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI & Images
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  
  # Utilities
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf